[package]
name = "vlab-binding"
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
vlab-core = { path = "../core" }
napi = { version = "=3.12.4", default-features = false, features = ["napi8", "dyn-symbols"] }
napi-derive = "=3.6.5"

[build-dependencies]
napi-build = "=2.4.2"
